blank_issues_enabled: false
contact_links:
  - name: 💬 Discussão técnica
    url: https://github.com/V-tal/enterprise.orchestration.privado.api.ms.resource.catalog/discussions
    about: Use discussões para brainstorm ou dúvidas antes de abrir uma issue
