name: Check Code Quality

on: 
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  check-lint-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install packages
      run: npm ci
    
    - name: Check linting
      run: npm run lint

    - name: Check build
      run: npm run build
